Repository JayTSmith/battleship-lua, pull requests merged in 2020-11, with the labels that each got.

#19 Foundation for the save/resume system
  game/data/game.lua
  game/data/settings.lua
  game/gui/screens/placement_screen.lua
  game/gui/screens/setup_screen.lua
  game/util/util.lua
  main.lua
Labels: enhancement

#20 Cleaning game_screen code
  game/gui/screens/game_screen.lua
Labels: documentation

#32 Big Feature List including cleaner screens, bug fixes, and harder AI code
  game/data/ai.lua
  game/gui/screens/ending_screen.lua
  game/gui/screens/placement_screen.lua
  game/gui/screens/play_screen.lua
  game/gui/screens/screen_manager.lua
  game/gui/screens/setup_screen.lua
  game/gui/screens/title_screen.lua
  game/gui/widgets/game_grid.lua
  game/util/util.lua
  main.lua
Labels: documentation, enhancement
